# Spam emails classifier

In [87]:
#import required libraries
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import string
import re
from sklearn.feature_extraction.text import CountVectorizer

In [88]:
#import required data
data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Email-spam-detection/master/emails.csv")

In [6]:
data

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [8]:
data.shape

(5728, 2)

In [9]:
data.isna().sum()

text    0
spam    0
dtype: int64

In [10]:
data.drop_duplicates(inplace = True)

In [11]:
data.shape

(5695, 2)

download stopwords and using string punctuation and stopwords remove all stop words

In [12]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pavanreddy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
def process(text):
    nonpunc = [char for char in text if char not in string.punctuation]
    nonpunc = "".join(nonpunc)
    clean = [word for word in nonpunc.split() if word.lower() not in stopwords.words("english")]
    return clean

In [17]:
data['text'].apply(process)

0       [Subject, naturally, irresistible, corporate, ...
1       [Subject, stock, trading, gunslinger, fanny, m...
2       [Subject, unbelievable, new, homes, made, easy...
3       [Subject, 4, color, printing, special, request...
4       [Subject, money, get, software, cds, software,...
                              ...                        
5723    [Subject, research, development, charges, gpg,...
5724    [Subject, receipts, visit, jim, thanks, invita...
5725    [Subject, enron, case, study, update, wow, day...
5726    [Subject, interest, david, please, call, shirl...
5727    [Subject, news, aurora, 5, 2, update, aurora, ...
Name: text, Length: 5695, dtype: object

In [19]:
data.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [29]:
data['text'] =data['text'].map(lambda x: re.sub("[^a-zA-Z]" , " " ,x))

In [55]:
data

text  spam
0     Subject  naturally irresistible your corporate...     1
1     Subject  the stock trading gunslinger  fanny i...     1
2     Subject  unbelievable new homes made easy  im ...     1
3     Subject    color printing special  request add...     1
4     Subject  do not have money   get software cds ...     1
...                                                 ...   ...
5723  Subject  re   research and development charges...     0
5724  Subject  re   receipts from visit  jim    than...     0
5725  Subject  re   enron case study update  wow   a...     0
5726  Subject  re   interest  david    please   call...     0
5727  Subject  news   aurora       update  aurora ve...     0

[5695 rows x 2 columns]

seperating the input and output

In [56]:
X = data.iloc[: , 0]
y= data.iloc[: , -1]

In [57]:
X

0       Subject  naturally irresistible your corporate...
1       Subject  the stock trading gunslinger  fanny i...
2       Subject  unbelievable new homes made easy  im ...
3       Subject    color printing special  request add...
4       Subject  do not have money   get software cds ...
                              ...                        
5723    Subject  re   research and development charges...
5724    Subject  re   receipts from visit  jim    than...
5725    Subject  re   enron case study update  wow   a...
5726    Subject  re   interest  david    please   call...
5727    Subject  news   aurora       update  aurora ve...
Name: text, Length: 5695, dtype: object

In [58]:
y

0       1
1       1
2       1
3       1
4       1
       ..
5723    0
5724    0
5725    0
5726    0
5727    0
Name: spam, Length: 5695, dtype: int64

using countvectorizer convert it into binary type

In [59]:
cv = CountVectorizer(max_features = 9000)

In [60]:
X = cv.fit_transform(X).toarray()

In [61]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [62]:
y =y.values

In [65]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [63]:
cv.get_feature_names()

['aa',
 'aaa',
 'aaron',
 'ab',
 'abacha',
 'abacus',
 'abbott',
 'abhay',
 'abilities',
 'ability',
 'able',
 'abn',
 'about',
 'above',
 'abovenet',
 'abroad',
 'absence',
 'absolute',
 'absolutely',
 'absorb',
 'abstract',
 'abu',
 'abuse',
 'ac',
 'academia',
 'academic',
 'academics',
 'acadia',
 'accelerate',
 'accelerated',
 'accept',
 'acceptable',
 'acceptance',
 'accepted',
 'accepting',
 'accepts',
 'access',
 'accessed',
 'accessible',
 'accessing',
 'accessories',
 'accident',
 'accidents',
 'accommodate',
 'accommodation',
 'accommodations',
 'accomodate',
 'accompanied',
 'accompany',
 'accompanying',
 'accomplish',
 'accomplished',
 'accomplishment',
 'accomplishments',
 'accord',
 'accordance',
 'according',
 'accordingly',
 'account',
 'accountability',
 'accountant',
 'accountants',
 'accounting',
 'accounts',
 'accrual',
 'accumulated',
 'accuracy',
 'accurate',
 'accurately',
 'achieve',
 'achieved',
 'achievements',
 'achieving',
 'ack',
 'acknowledged',
 'acknowl

In [64]:
len(cv.get_feature_names())

9000

split the data and apply the suitable algorithm

In [66]:
from sklearn.model_selection import train_test_split

In [72]:
X_train , X_test , y_train , y_test = train_test_split(X  , y , test_size = 0.2 , random_state = 30)

In [73]:
X_train.shape

(4556, 9000)

In [74]:
X_test.shape

(1139, 9000)

In [75]:
y_train.shape

(4556,)

In [76]:
y_test.shape

(1139,)

In [77]:
from sklearn.naive_bayes import MultinomialNB

In [78]:
classifier = MultinomialNB().fit(X_train , y_train)

In [80]:
y_pred = classifier.predict(X_test)

In [81]:
from sklearn.metrics import accuracy_score

In [85]:
accuracy_score(y_test , y_pred)*100

98.4196663740123

Hence accuracy score is 98.4196663740123

In [92]:
from sklearn.metrics import confusion_matrix

In [93]:
confusion_matrix(y_test , y_pred)

array([[876,  15],
       [  3, 245]], dtype=int64)